moved service management and check scripts into helper.sh to be reusable by dwh package

diff --git a/src/debian/postinst b/src/debian/postinst
--- a/src/debian/postinst
+++ b/src/debian/postinst
@@ -11,30 +11,14 @@
 
 readonly OPERATION="${1}"
 
-check_and_start_services() {
-  local services=("apache2" "postgresql" "wildfly")
-  local max_retries=5
-  local retry_delay=5
-  echo "Starting required services..."
-
-  for service in "${services[@]}"; do
-    if systemctl is-active --quiet "${service}"; then
-      continue
-    fi
-
-    for ((i=1; i<=max_retries; i++)); do
-      systemctl start "${service}"
-      sleep "${retry_delay}"
-      if systemctl is-active --quiet "${service}"; then
-        break
-      fi
-      if [ "$i" -eq "$max_retries" ]; then
-        echo "Error: Failed to start ${service} after ${max_retries} attempts" >&2
-        exit 1
-      fi
-      echo "Retry ${i}/${max_retries} for ${service}"
-    done
-  done
+source_helper_script() {
+  local helper_path="/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
+  echo "Loading helper script..."
+  if [[ ! -f "${helper_path}" ]]; then
+    echo "Error: helper.sh not found at ${helper_path}" >&2
+    exit 1
+  fi
+  . "${helper_path}"
 }
 
 activate_php_curl_extension() {
@@ -59,22 +43,10 @@ check_postgresql_versions() {
   fi
 }
 
-source_helper_script() {
-  local helper_path="/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
-  echo "Loading helper script..."
-  if [[ ! -f "${helper_path}" ]]; then
-    echo "Error: helper.sh not found at ${helper_path}" >&2
-    exit 1
-  fi
-  . "${helper_path}"
-}
-
 init_and_seed_i2b2_database() {
-  source_helper_script
   connect_to_psql
   wait_for_psql_connection
   echo "Initializing i2b2 database..."
-
   if [[ $(eval "${PSQL} -l" | grep "i2b2" | wc -l) == 0 ]]; then
     eval "${PSQL} -v ON_ERROR_STOP=1 -f /usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/sql/i2b2_init.sql" >/dev/null
     eval "${PSQL} -v ON_ERROR_STOP=1 -d i2b2 -f /usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/sql/i2b2_db.sql" >/dev/null
@@ -147,6 +119,7 @@ main() {
   case "$OPERATION" in
     configure)
       # Runs during installation/upgrade after files have been unpacked.
+      source_helper_script
       dpkg-trigger --no-await "${DPKG_MAINTSCRIPT_PACKAGE}"/restore
       check_and_start_services
       activate_php_curl_extension
diff --git a/src/debian/postrm b/src/debian/postrm
--- a/src/debian/postrm
+++ b/src/debian/postrm
@@ -10,6 +10,16 @@
 
 readonly OPERATION="${1}"
 
+source_temp_helper() {
+  echo "Loading temporary helper script..."
+  local temp_helper="/tmp/${DPKG_MAINTSCRIPT_PACKAGE}_helper.sh"
+  if [[ ! -f "${temp_helper}" ]]; then
+    echo "Error: Helper script not found at ${temp_helper}" >&2
+    return 1
+  fi
+  source "${temp_helper}"
+}
+
 deactivate_php_curl_extension() {
   echo "Deactivating PHP curl extension..."
   if grep -q "^extension=curl" /etc/php/*/apache2/php.ini; then
@@ -51,16 +61,6 @@ To disable them if no longer needed:
 EOF
 }
 
-source_temp_helper() {
-  echo "Loading temporary helper script..."
-  local temp_helper="/tmp/${DPKG_MAINTSCRIPT_PACKAGE}_helper.sh"
-  if [[ ! -f "${temp_helper}" ]]; then
-    echo "Error: Helper script not found at ${temp_helper}" >&2
-    return 1
-  fi
-  source "${temp_helper}"
-}
-
 drop_i2b2_database() {
   echo "Removing i2b2 database..."
   if ! command -v psql >/dev/null 2>&1 || ! systemctl is-active --quiet postgresql; then
@@ -68,7 +68,6 @@ drop_i2b2_database() {
     return 0
   fi
 
-  source_temp_helper
   connect_to_psql
   wait_for_psql_connection
   if [[ $(eval "${PSQL} -l" | grep "i2b2" | wc -l) -gt 1 ]]; then
@@ -110,6 +109,7 @@ main() {
       ;;
     purge)
       # Runs during a purge after 'postrm remove' to delete all leftover files.
+      source_temp_helper
       drop_i2b2_database
       delete_wildfly_backup_logs
       remove_temp_helper
diff --git a/src/debian/prerm b/src/debian/prerm
--- a/src/debian/prerm
+++ b/src/debian/prerm
@@ -9,6 +9,16 @@
 
 readonly OPERATION="${1}"
 
+source_helper_script() {
+  local helper_path="/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
+  echo "Loading helper script..."
+  if [[ ! -f "${helper_path}" ]]; then
+    echo "Error: helper.sh not found at ${helper_path}" >&2
+    exit 1
+  fi
+  . "${helper_path}"
+}
+
 # Creates temporary helper.sh in /tmp/ as helper.sh would be deleted before postrm and is required for database connection
 create_temp_helper() {
   echo "Creating temporary helper script..."
@@ -46,6 +56,8 @@ main() {
       ;;
     upgrade)
       # Runs during package upgrade before installation of new package.
+      source_helper_script
+      stop_wildfly
       dpkg-trigger --no-await "${DPKG_MAINTSCRIPT_PACKAGE}"/backup
       backup_wildfly_logs
       ;;
