added missing debconf for db credentials for postrm purge

diff --git a/src/debian/postrm b/src/debian/postrm
--- a/src/debian/postrm
+++ b/src/debian/postrm
@@ -35,9 +35,43 @@ delete_wildfly_user() {
   fi
 }
 
+connect_to_psql() {
+  . /usr/share/debconf/confmodule
+  local debconf_name
+  debconf_name=$(echo "$DPKG_MAINTSCRIPT_PACKAGE" | awk -F '-' '{print $1"-"$2}')
+
+  db_get "${debconf_name}/db_conn"
+  if [ "$RET" = "unix" ]; then
+    readonly PSQL="sudo -u postgres psql"
+    echo "Connecting to postgres via local unix socket."
+  else
+    db_get "${debconf_name}/db_host"; local host="$RET"
+    db_get "${debconf_name}/db_port"; local port="$RET"
+    db_get "${debconf_name}/db_user"; local user="$RET"
+    db_get "${debconf_name}/db_pass"; local pass="$RET"
+    readonly PSQL="psql postgresql://${user}:${pass}@${host}:${port}?sslmode=require"
+    echo "Connecting to postgres via TCP/IP to $host:$port."
+  fi
+}
+
+wait_for_psql_connection() {
+  local waitcount=0
+  while ! systemctl start postgresql 2>/dev/null; do
+    if [ "$waitcount" -lt 12 ]; then
+      echo "Database not yet installed. Waiting ..."
+      waitcount=$((waitcount + 1))
+      sleep 5
+    else
+      echo "Database not yet installed. Aborting ..."
+      exit 1
+    fi
+  done
+  systemctl enable postgresql.service
+}
+
 drop_i2b2_database() {
   echo "Dropping i2b2 PostgreSQL database and user..."
-  eval "sudo -u postgres psql -v ON_ERROR_STOP=1" <<EOF >/dev/null
+  eval "${PSQL} -v ON_ERROR_STOP=1" <<EOF >/dev/null
 __I2B2_DROP_STATEMENT__
 
 EOF
@@ -48,11 +82,12 @@ main() {
   case "$OPERATION" in
     remove)
       deactivate_php_curl_extension
-      enable_psql_updates
       delete_wildfly_remnants
       delete_wildfly_user
       ;;
     purge)
+      connect_to_psql
+      wait_for_psql_connection
       drop_i2b2_database
       ;;
   esac
