moved db connection methods into helper.sh, refactored postinst

diff --git a/src/debian/postinst b/src/debian/postinst
--- a/src/debian/postinst
+++ b/src/debian/postinst
@@ -1,14 +1,41 @@
 #!/bin/bash
 #--------------------------------------
 # Script Name:  postinst
-# Version:      1.0
+# Version:      1.1
 # Author:       skurka@ukaachen.de, shuening@ukaachen.de, akombeiz@ukaachen.de
-# Date:         25 Oct 24
-# Purpose:      Post-installation script for 'aktin-notaufnahme-i2b2'. It configures services, initializes the i2b2 database, sets up users and
-#               permissions, and ensures all components are enabled and started correctly.
+# Date:         30 Oct 24
+# Purpose:      Post-installation script for 'aktin-notaufnahme-i2b2'. Configures services, initializes the i2b2 database, sets up users and
+#               permissions, ensures all components are enabled and started correctly.
 #--------------------------------------
 
 readonly OPERATION="${1}"
+
+source_helper_script() {
+  local helper_path="/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
+  if [[ -f "${helper_path}" ]]; then
+    . "${helper_path}"
+  else
+    echo "Error: helper.sh not found at ${helper_path}" >&2
+    exit 1
+  fi
+}
+
+check_and_start_services() {
+  local services=("apache2" "postgresql" "wildfly")
+  for service in "${services[@]}"; do
+    if ! systemctl is-active --quiet "${service}"; then
+      echo "Service ${service} is not running. Starting ${service}..."
+      systemctl start "${service}"
+      if ! systemctl is-active --quiet "${service}"; then
+        echo "Error: Failed to start ${service}." >&2
+        exit 1
+      fi
+    else
+      echo "Service ${service} is already running."
+    fi
+  done
+  echo "All services are running."
+}
 
 activate_php_curl_extension() {
   if grep -q ";extension=curl" /etc/php/*/apache2/php.ini; then
@@ -21,41 +48,10 @@ activate_php_curl_extension() {
   fi
 }
 
-connect_to_psql() {
-  . /usr/share/debconf/confmodule
-  local debconf_name
-  debconf_name=$(echo "$DPKG_MAINTSCRIPT_PACKAGE" | awk -F '-' '{print $1"-"$2}')
-
-  db_get "${debconf_name}/db_conn"
-  if [ "$RET" = "unix" ]; then
-    readonly PSQL="sudo -u postgres psql"
-    echo "Connecting to postgres via local unix socket."
-  else
-    db_get "${debconf_name}/db_host"; local host="$RET"
-    db_get "${debconf_name}/db_port"; local port="$RET"
-    db_get "${debconf_name}/db_user"; local user="$RET"
-    db_get "${debconf_name}/db_pass"; local pass="$RET"
-    readonly PSQL="psql postgresql://${user}:${pass}@${host}:${port}?sslmode=require"
-    echo "Connecting to postgres via TCP/IP to $host:$port."
-  fi
-}
-
-wait_for_psql_connection() {
-  local waitcount=0
-  while ! systemctl start postgresql 2>/dev/null; do
-    if [ "$waitcount" -lt 12 ]; then
-      echo "Database not yet installed. Waiting ..."
-      waitcount=$((waitcount + 1))
-      sleep 5
-    else
-      echo "Database not yet installed. Aborting ..."
-      exit 1
-    fi
-  done
-  systemctl enable postgresql.service
-}
-
 init_and_seed_i2b2_database() {
+  source_helper_script
+  connect_to_psql
+  wait_for_psql_connection
   if [[ $(eval "${PSQL} -l" | grep "i2b2" | wc -l) == 0 ]]; then
     echo "Creating i2b2 database and users ..."
     eval "${PSQL} -v ON_ERROR_STOP=1 -f /usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/database/i2b2_init.sql" >/dev/null
@@ -66,10 +62,10 @@ init_and_seed_i2b2_database() {
   fi
 }
 
+# TODO: Workaround for insufficient connection handling of WildFly datasources. Replace as soon as possible.
 set_wildfly_service_dependency() {
-  # Workaround for insufficient connection handling of WildFly datasources. Replace as soon as possible.
   echo "Setting up service dependency between postgresql and wildfly ..."
-  . "/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
+  source_helper_script
   add_entry_to_service "wildfly.service" "Requires" "postgresql.service"
   add_entry_to_service "wildfly.service" "After" "postgresql.service"
 }
@@ -81,37 +77,36 @@ create_wildfly_user() {
   chown wildfly:wildfly /opt/wildfly/standalone/deployments/*
 }
 
-remove_i2b2_config_data() {
-  local i2b2_config_data_path="/var/www/html/webclient/i2b2_config_data.js"
-  if [ -f "$i2b2_config_data_path" ]; then
-    rm "$i2b2_config_data_path"
-  fi
-}
+#remove_i2b2_config_data() {
+#  local i2b2_config_data_path="/var/www/html/webclient/i2b2_config_data.js"
+#  if [[ -f "$i2b2_config_data_path" ]]; then
+#    rm "$i2b2_config_data_path"
+#  fi
+#}
 
 main() {
   set -euo pipefail
   case "$OPERATION" in
     configure)
+      # Run after installation or upgrade to complete configuration.
+      check_and_start_services
       activate_php_curl_extension
       systemctl enable apache2
-      connect_to_psql
-      wait_for_psql_connection
       init_and_seed_i2b2_database
       systemctl enable postgresql
       set_wildfly_service_dependency
       create_wildfly_user
       systemctl enable wildfly
-      systemctl start wildfly
       systemctl daemon-reload
+      ;;
+    abort-upgrade)
+      # Used to revert changes if an upgrade fails.
       ;;
     abort-remove)
-      systemctl enable wildfly || true
-      systemctl start wildfly || true
-      systemctl daemon-reload
+      # Handle tasks if a package removal is interrupted.
       ;;
-    upgrade)
-      #TODO Will never be called
-      remove_i2b2_config_data
+    abort-deconfigure)
+      # Used if a deconfiguration operation fails.
       ;;
   esac
 }
