added ToDo in postinst, refactored postrm and prerm, added script metadata, removed enabling of psql_updates (only limited to postgresql-12, didnt work anyway), updated console comments,

diff --git a/src/debian/prerm b/src/debian/prerm
--- a/src/debian/prerm
+++ b/src/debian/prerm
@@ -1,22 +1,41 @@
 #!/bin/bash
+#--------------------------------------
+# Script Name:  prerm
+# Version:      1.0
+# Author:       skurka@ukaachen.de, shuening@ukaachen.de, akombeiz@ukaachen.de
+# Date:         25 Oct 24
+# Purpose:      Pre-removal script that stops and disables the WildFly service
+#               before the 'aktin-notaufnahme-i2b2' package is removed or upgraded.
+#--------------------------------------
+
 set -euo pipefail
 
 readonly OPERATION="${1}"
 
-function main() {
-    set -euo pipefail
-    case "${OPERATION}" in
+main() {
+  case "$OPERATION" in
     remove)
+      echo "Stopping and disabling WildFly service..."
+      if systemctl is-active --quiet wildfly; then
         systemctl stop wildfly || true
-        systemctl disable wildfly || true
-        systemctl daemon-reload
-        ;;
+      else
+        echo "WildFly service is not running."
+      fi
+      systemctl disable wildfly || true
+      systemctl daemon-reload
+      ;;
     upgrade)
+      echo "Removing WildFly-Postgresql service dependencies..."
+      if [ -f "/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh" ]; then
         . "/usr/share/${DPKG_MAINTSCRIPT_PACKAGE}/helper.sh"
         remove_entry_from_service "wildfly.service" "Requires" "postgresql.service"
         remove_entry_from_service "wildfly.service" "After" "postgresql.service"
-        ;;
-    esac
+        systemctl daemon-reload
+      else
+        echo "Helper script not found; skipping dependency removal."
+      fi
+      ;;
+  esac
 }
 
 main
